### ISSUE TITLE
Asus TUF 0RPM GPU Fan

### ISSUE THREAD

**Issue by haryosr** [seerge/g-helper#1913]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### What's wrong?

Everytime i turn on my Laptop (Asus TUF FX507ZR), i will have a bug where Manual mode (Using power limits or applying fan curve) will turn my gpu fan to 0RPM, untill i use eco mode to "refresh" my dgpu. After i switch it again to other gpu mode, using manual mode will work again.

What lead me to believe that it's not Ghelper fault :
https://www.reddit.com/r/ASUSROG/comments/10eudaq/gpu_fan_at_0_rpm_only_in_manual_mode_on_armory/

If you can, I want to request a feature to auto switch mode to eco and the mode before every time the system starting up.

Before Eco Mode :
https://www.youtube.com/watch?v=TI6TFnqmhXI
After Eco Mode :
https://www.youtube.com/watch?v=h-AYcikoMlA

### How to reproduce the bug?

Using Power Limits and Fan Curve after every startup.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/13928773/log.txt)

### Device and Model

Asus TUF FX507ZR

### Asus Software Running

- [ ] Armoury Crate
- [ ] MyAsus
- [ ] Other Asus Services

### Version

0.146

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@haryosr hello, it's indeed not G-Helper's fault as this is simply bugged BIOS.

You can already do that: 

- Just check "Enable GPU on shutdown" under ``Extra```
- Select Optimized mode (it will set GPU off again if you are on battery every time app starts)

**Comment by haryosr** [comment]
So yeah, under optimized mode, i can replug my charger to fix the bug. (i think it's because unplugging puts me into eco mode tho)
But Enabling GPU on shutdown under Extra, doesnt fix the bug automaticaly.

I am able to "fix" the problem temporarily by replugging the charger, or going eco on the app for a sec, so i guess its alright.
Thank you for replying so quickly.

**Comment by seerge** [comment]
@haryosr can you quickly try this build instead

[GHelper.zip](https://github.com/seerge/g-helper/files/13928904/GHelper.zip)

I have removed a special "manual mode" flag that your device required in order to allow custom (optional) power limits to work

And please test

1. If fan behavior changes?
2. If custom power limits work (after you apply them with ``Apply`` checkbox)

**Comment by haryosr** [comment]
The fan is now working if Power Limits is checked, but custom Fan Curve is left unchecked

**Comment by haryosr** [comment]
my bad, the gpu fan is on, but the power limits it self doesnt work.
Here is the video of me using it :
https://www.youtube.com/watch?v=494hnc6CYXM
I hope u can still see whats going on since the video is still processing

**Comment by seerge** [comment]
@haryosr ok, so power limits are **not working** - making custom mode useless, correct ?

**Comment by haryosr** [comment]
yea, that seems to be the case

**Comment by seerge** [comment]
@haryosr ok. Well then it looks like setting a "manual mode" flag is the only way to make power limits work on your device (same as it was done already). That manual mode is turned on only, if you have ``Apply`` checked next to power limits.

As for ``Turn GPU on shutdown``, did you try to reboot after that ?

Main idea is that when your laptop starts, GPU is ON (check this topic for more details https://github.com/seerge/g-helper/discussions/1042)

**Comment by seerge** [comment]
P.S. Do you have latest BIOS version ?

**Comment by haryosr** [comment]
Turn GPU on Shutdown isn't working since the bug are not starting by booting in eco. As for bios, yes i have the latest since i just installed ghelper 2 days ago and i did update my bios from MyAsus before uninstalling it.
![image](https://github.com/seerge/g-helper/assets/156528429/ad68375b-25a9-4540-981b-565ebc250d57)

**Comment by haryosr** [comment]
I did remember that i face the same problem when trying in armoury crate before, but not in the latest bios. So i dont know if there is a fix.

**Comment by seerge** [comment]
@haryosr well, I don't want to add any tricky GPU restarts to the app itself as I don't know the consequences.

But if you really want - you can just use powershell commands (run as admin), that do same thing as G-Helper does to turn GPU OFF or ON

Set ECO mode (GPU OFF)
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1)
```

Set STANDARD mode (GPU ON)
```
(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 0)
```

You can just run them together on startup or do a small bat file for that :)

**Comment by seerge** [comment]
P.S. Bat file contents would look something like that

```
powershell -Command "(Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 1); (Get-WmiObject -Namespace Root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00090020, 0)"
```

But again, it's all up to you and your risk :)

I'm closing this, as that's maximum I can offer.

Good luck

**Comment by seerge** [comment]
@haryosr Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks

**Comment by haryosr** [comment]
Lets try

**Comment by haryosr** [comment]
![image_2024-03-23_213929325](https://github.com/seerge/g-helper/assets/156528429/beb3de7f-300d-49c2-be26-82e07bca6b38)
The build included there still having the issue of 0 rpm read, although i'm can't really say for sure that the fan is spinning or not

**Comment by seerge** [comment]
@haryosr you need to click ``Apply Custom Fan Curve``

**Comment by haryosr** [comment]
![image_2024-03-23_215117376](https://github.com/seerge/g-helper/assets/156528429/799b1fcf-07c4-4afd-b50f-d2123ba2da29)
This is with the apply custom fan curve checked, the gpu fan is indeed showing percentage, but if i put my hand on the airflow to feel the air, i will say that it doesn't give the same blow as the cpu airflow output, or even any blow at all. 
I did confirm my self that i can feel the blow on auto fan settings.

**Comment by seerge** [comment]
@haryosr ok.

Does GPU fan ever spin in your case?

Can you run a fan test under MyASUS to see if it is able to speen it up ? Cause G-Helper currently uses the same command as MyASUS under it's fan tester.

**Comment by haryosr** [comment]
This one is under Custom Fan Curve Checked. Does have the blow.
![image](https://github.com/seerge/g-helper/assets/156528429/251f7889-6cff-4bd8-b946-f47d99aa97d1)
This one is after getting the result and letting the fan.
![image_2024-03-23_221637512](https://github.com/seerge/g-helper/assets/156528429/b264ee54-67d5-4efc-8464-f5561cd0c33c)
And this one is with heaven benchmark with the custom fan curve checked. Doesn't have the blow.
![image_2024-03-23_222042535](https://github.com/seerge/g-helper/assets/156528429/d17afc25-6d07-4657-8dda-31363a774507)

**Comment by seerge** [comment]
@haryosr ok, so MyAsus tester manages to spin it somehow.

Can you check this build and let me know if it makes any difference ?
[GHelper.zip](https://github.com/seerge/g-helper/files/14733266/GHelper.zip)

**Comment by haryosr** [comment]
The fan is working. I feel the blow too!
![image](https://github.com/seerge/g-helper/assets/156528429/e838c8c4-06a9-4e35-a030-2d61e2448da4)
it does follow the power limit, but not the curve though.
It does somewhat follow the curve, but with some offset, like around +800rpm.
![image_2024-03-24_042150081](https://github.com/seerge/g-helper/assets/156528429/9f5b9047-2a76-43fc-ad0c-94ab48fafb28)

**Comment by seerge** [comment]
@haryosr i have added fan calibration button for your model, if you will do that it may improve RPM on Y-axis, so it should be a bit closer than 800
[GHelper.zip](https://github.com/seerge/g-helper/files/14733740/GHelper.zip)

**Comment by haryosr** [comment]
Hey, I am afraid that there might have been some fucked up around my part. I am sure that I have run some test and do atleast a restart before sending the result here. But I cant reproduce of what happened before and the gpu fan is now at 0 RPM again.
![image](https://github.com/seerge/g-helper/assets/156528429/0756011e-e6c0-4cc4-8a05-9494feb98c1c)

This is me trying to test it again with myAsus and the ghelper you just sent out.
![image](https://github.com/seerge/g-helper/assets/156528429/031dc209-fa73-47a4-93e6-37bc55b1596d)

This is what happened when i pressed calibrate button after letting the fan.
![image](https://github.com/seerge/g-helper/assets/156528429/4c1c9704-8200-4402-ba25-b6ce5094e27e)

This is a weird gpu fan working (inside calibrate/just after calibrate is done) but then it went back to 0.
![image](https://github.com/seerge/g-helper/assets/156528429/9657d519-ee9f-461d-9241-576ba015408b)

-------
I'm really confused of what happened or what is the difference before, but i just cant reproduce of what happened.

**Comment by haryosr** [comment]
![image](https://github.com/seerge/g-helper/assets/156528429/bc545297-1d9a-4bff-8e60-117a98df78f4)
This is what happened if i replug the power, as usual it will work, and probably the only possible explaination as to what happened before, even though i am quite sure that i did not replug the power.

this is the version of MyAsus that i have. since weirdly enough the calibrate is working after i replug the power
![image](https://github.com/seerge/g-helper/assets/156528429/04aba612-8c89-49d5-8fd0-d9db8b127c08)

**Comment by haryosr** [comment]
![image](https://github.com/seerge/g-helper/assets/156528429/77ebac31-f3ad-4ecc-85dc-787ede5226f7)
There is still about +800RPM offset if you still wonder about the offset at this point.

I'm sorry i failed you bro.

**Comment by seerge** [comment]
@haryosr i didn't really get it. Is it not working at all ? Or working, but you see a different speed measurements ? 

Cause the only thing calibration does is sets fans to 100%, and measures how much RPM is that. And adjusts Y-scale based on it. But it could be that fans have some weird behavior in your case, and when they are set to 70% for example, in reality just spin a bit slower. It's almost impossible to achieve higher granularity here :)

**Comment by haryosr** [comment]
It's not working.

What i meant by "working as usual" is to throw us back to January when we found out that the whole power limits, and fan curve problem can be fixed by replugging the power cable.
what is happening right now: 
1. Calibration function only works after replugging the power cable.
2. In a fresh startup (with power already plugged) the calibration function will not work until you replugging power.
3. MyASUS still somehow managed to test both fan, and that's why i show you my version of myasus, i did it just because there could be a variable.
4. Running MyASUS fan test doesn't fix the problem like replugging power does.
Although i think my gpu fan in this case actually just don't spin (i don't further confirm this by opening the case and just draw conclusions by feeling the blow or hearing the fan), i can certainly agree that this weird fan behavior can only be just my case.

**Comment by haryosr** [comment]
Just lemme know if you have anything else for me to test, and I'll be happy to test it.

**Comment by seerge** [comment]
@haryosr try this build and post a log from it please
[GHelper.zip](https://github.com/seerge/g-helper/files/14735141/GHelper.zip)

**Comment by haryosr** [comment]
![image](https://github.com/seerge/g-helper/assets/156528429/ae3ed7c9-d28c-4bd4-893a-d30f7f202ae0)
At the moment, i havent replugging power, restart and shutdown a couple of time, and the fan does have the blow and i can hear it spinning.
[log.txt](https://github.com/seerge/g-helper/files/14735282/log.txt)

**Comment by haryosr** [comment]
oh and the calibrate button does bring the fan to max

**Comment by seerge** [comment]
@haryosr so it's all working as it should ?

**Comment by haryosr** [comment]
It is! i might add that after 1/2 time of restarting, i run auto startup and it is still working

**Comment by haryosr** [comment]
After some more testing, I found that the rpm wouldn't come down after you press calibrate and bypassing the limit. Although closing the program you're running and letting fan rpm below the limit does do the trick.

Regular Test run.
![image](https://github.com/seerge/g-helper/assets/156528429/d82a65da-e21a-46e2-884d-08c37cc51f3a)

Pressing calibrate in a test run.
![image](https://github.com/seerge/g-helper/assets/156528429/2d5a9b88-ca8f-41b1-993f-263fa5b24737)

A test run after the calibrate phase is over.
![image](https://github.com/seerge/g-helper/assets/156528429/f3a648a0-57fb-491f-91f1-a81676f7f2f1)

A test run after letting the cpu temp and RPM lowered down.
![image](https://github.com/seerge/g-helper/assets/156528429/45b401ef-f434-4437-8088-e80bd6e693ca)

**Comment by haryosr** [comment]
The sound that the fan produces seems to match the rpm, and not the percentage.
[A test run after the calibrate phase is over.] image picture what i mean.

**Comment by seerge** [comment]
@haryosr that's just calibration not ending correctly, just download latest release from main post at https://github.com/seerge/g-helper/discussions/2272 , i think i have fixed that already

**Comment by haryosr** [comment]
I still have that issue with the new ghelper from #2272 .
![image](https://github.com/seerge/g-helper/assets/156528429/c2273e75-5d6b-43eb-9e5d-4ebdbb136df9)

To me, you already did something amazing to my laptop by allowing me to do these fan curve, although it still also have the offset mentioned before even after calibration. Just want to let you know that this is already really nice for me, and that just a minor issue. Thank you!

**Comment by seerge** [comment]
@haryosr can you try this build ?

As for offset - can you check how accurate it is in 3 different situations

- Minimal speed (i.e. like just above 0)
- Mid speed (ie. around center)
- Max speed

Cause after calibration Min and Max speeds should be accurate
[GHelper.zip](https://github.com/seerge/g-helper/files/14735723/GHelper.zip)

**Comment by haryosr** [comment]
Test was ran after calibration.

Min.
![image](https://github.com/seerge/g-helper/assets/156528429/24f888a5-ea2c-4a3c-ab15-cf8cfa6c1ef0)

Mid.
![image](https://github.com/seerge/g-helper/assets/156528429/85d31627-fc1a-4bbb-9dad-159cdcb0b316)

Max.
![image](https://github.com/seerge/g-helper/assets/156528429/26ef2ff8-7aaf-483c-9c22-2918ad94d362)

**Comment by seerge** [comment]
@haryosr this build  should improve matching a bit :)

[GHelper.zip](https://github.com/seerge/g-helper/files/14741257/GHelper.zip)

**Comment by haryosr** [comment]
This is ran after calibration.

Min.
![image](https://github.com/seerge/g-helper/assets/156528429/3fc84f6b-7fca-43f7-8de4-d9e71094729c)

Mid.
![image](https://github.com/seerge/g-helper/assets/156528429/89828690-3211-4288-9b06-fcf6f4ab7111)

Max.
![image](https://github.com/seerge/g-helper/assets/156528429/170a6fb5-d1bc-4dff-a911-010d571ddd04)

**Comment by seerge** [comment]
@haryosr ok, it looks like system overrides minimum fan speed heavily in your case. It sets 25% (in red label) and they keep running on much higher speed instead

**Comment by seerge** [comment]
@haryosr if you want to you can try build that will allow to set minimim fan speed to as low as 1% :) i wonder if it will affect actual minimum speed in your case or it will stay around 2400 or so

[GHelper.zip](https://github.com/seerge/g-helper/files/14746268/GHelper.zip)

**Comment by haryosr** [comment]
I'm running the minimum at the lowest number before off, max/2 for the middle, and all the way for the max.

The test was ran after calibration.

Min.
![image](https://github.com/seerge/g-helper/assets/156528429/a3d0c8bc-0738-414a-8eae-1e5a4149692d)

Mid.
![image](https://github.com/seerge/g-helper/assets/156528429/9d171299-1a7b-4120-83cc-f2440057a5a8)

Max.
![image](https://github.com/seerge/g-helper/assets/156528429/4a1bdc3f-8de5-4db0-9251-cd7c27f9f717)

**Comment by seerge** [comment]
@haryosr try to slowly drag them from lowest 1% (as then they are simply OFF) to something like 5% or 10% to see what is the actual minimum fan speed your device can handle.

**Comment by haryosr** [comment]
![image](https://github.com/seerge/g-helper/assets/156528429/17735339-2e35-458d-930c-f922799ea25a)
it seems like the fan will only spin if i set it to 2000rpm atleast, even though they will run it at 1200-1400rpm as written on the ghelper.
But at that point the fan will not enough to sustain the temp, and will get new rpm matching to the fool proof.

I only do calibration once after running the new fixes you sent.
