### ISSUE TITLE
[Bug] Boxes arround text are back in v0.59

### ISSUE THREAD

**Issue by marcelomijas** [seerge/g-helper#346]
**Describe the bug**
The new v0.59 introduces boxes around text in the Extra options (again). This time in the "Backlight" section, it also cuts the text of an option "En suspensi" should display as "En suspensión". :)

**Clear scenario to Reproduce**
1. Download v0.59
2. Start the app.

**Expected behavior**
No boxes around text in the "Backlight" section (like in the previous version).

**App Logs**
```
09/05/2023 16:35:49: ------------
09/05/2023 16:35:49: App launched: ROG Zephyrus G14 GA401IV_GA401IV :0.59.0.0
09/05/2023 16:35:49: AutoSetting for Online
09/05/2023 16:35:50: PerformanceMode = 0 : OK
09/05/2023 16:35:50: FanCPU = 14-1E-31-3C-49-50-59-64-00-00-08-18-1F-28-36-3A : OK
09/05/2023 16:35:50: FanGPU = 14-1D-32-3B-48-4C-51-64-01-01-09-10-10-22-34-3E : OK
09/05/2023 16:35:50: Boost 0
09/05/2023 16:35:50: Eco flag : -65536
09/05/2023 16:35:50: Mux flag : -65536
09/05/2023 16:35:51: Screen = 120Hz : OK
09/05/2023 16:35:51: ScreenOverdrive = 0 : 0
09/05/2023 16:35:51: Monitor Power On
```

**Screenshots or screencasts**

![v059](https://github.com/seerge/g-helper/assets/62946623/4d778381-b42c-4090-8c67-85c864cd09dc)

How it should be (v0.58):

![v058](https://github.com/seerge/g-helper/assets/62946623/9b704208-d8a8-4077-be1e-1cc86c6f72cd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GA401IV (G14 2020)

**Asus software**
- Asus Optimization Service

**Comment by marcelomijas** [comment]
@seerge now the boxes are gone, but the text of the third option is still cutted off, "En suspensi"(ón):

![imagen](https://github.com/seerge/g-helper/assets/62946623/195fa20e-ae6f-440b-a732-af2e4b7ba99d)

Thanks!

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11434489/GHelper.zip)
Fixed it :) thanks, but i will push it in next release as reupploading over old one each time resets statistics :(

**Comment by marcelomijas** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/11434489/GHelper.zip) Fixed it :) thanks, but i will push it in next release as reupploading over old one each time resets statistics :(

Ok @seerge , but this last version that you have passed still has the text cutting. Tried deleting the AppData folder and performing a clean install but it is still the same...

**Comment by seerge** [comment]
@marcelomijas this one should be fine : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11435591/GHelper.zip)
:)

**Comment by marcelomijas** [comment]
@seerge problem persists :')

I checked the translation, I see all ok there, it says "En suspensión".

![imagen](https://github.com/seerge/g-helper/assets/62946623/8fbe896c-426d-406d-b8c4-180ce15a10be)

**Comment by seerge** [comment]
@marcelomijas looks like scaling issue ... as i understand it's still win 10 ?
Another attempt:
[GHelper.zip](https://github.com/seerge/g-helper/files/11435928/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge Now is perfect again! Thanks a lot! :)

Yeah Windows 10... I tried 11 some months ago but I got back because of the performance impact...

![imagen](https://github.com/seerge/g-helper/assets/62946623/1aab8f8a-7b31-4fae-a90e-c68a802c54a8)
